services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
      - repo-web-node-modules:/workspace/node_modules
      - repo-web-nuxt:/workspace/.nuxt
      - repo-web-output:/workspace/.output
    ports:
      - "3000:3000"
    command: >
      sh -c "sudo chown -R node:node /workspace && 
        sleep infinity"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    user: root

volumes:
  repo-web-node-modules:
  repo-web-nuxt:
  repo-web-output: